[package]
name = "mc-status-rs"
version = "0.1.6"
edition = "2021"

[dependencies]
mcping = "0.2.0"
poise = "0.6.1"
env_logger = "0.11.5"
tokio = { version = "1.39.3", features = ["rt", "rt-multi-thread", "macros"] }
dotenv = "0.15.0"
