image: "ghcr.io/vaughnw128/mc-status-rs"
size: small
secretVars:
  DISCORD_TOKEN: "mc-status-rs-discord-token/credential"
envVars:
  MAPS_ADDRESS: "https://maps.vaughn.sh"
  MC_SERVER_IP: "mc.vaughn.sh"